server:
     port: 9000
spring:
  profiles.active: consti
logging:
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
---
spring:
  profiles: default
  datasource:
    reservation:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.217.129:5432/carrental
      username: postgres
      password: passme
    test:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.217.129:5432/carrental
      username: postgres
      password: passme2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  pickupPoint:
    mongo:
      host: 192.168.217.129
      name: carrental
  billing:
    mongo:
      host: 192.168.217.129
      name: carrental

---
spring:
  profiles: consti
  datasource:
    reservation:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.59.103:5432/carrental
      username: postgres
      password: passme
    test:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.59.103:5432/carrental
      username: postgres
      password: passme2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  pickupPoint:
    mongo:
      host: 192.168.59.103
      name: carrental
  billing:
    mongo:
      host: 192.168.59.103
      name: carrental