server:
     port: 9000
spring:
  profiles.active: default
---
spring:
  profiles: default
  datasource:
    reservation:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.217.129:5432/carrental
      username: postgres
      password: passme
    test:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.217.129:5432/carrental
      username: postgres
      password: passme2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop